[General]
timeframe = 5m
currency_pairs = ETH/USDT,STX/USDT,AVAX/USDT,SUI/USDT
initdata_num = 2000
onmessage = true

[database]
; 数据库类型: sqlite3 | postgresql
db_type = sqlite3
; SQLite3 数据库文件路径
db_path = ./data.db
; PostgreSQL 连接字符串
db_conn = host=localhost port=5432 dbname=hhjrdata user=hhjr password=hhjr

[Exchange]
exchange_id = binance
base_url = https://fapi.binance.com

[Proxy]
proxy_url = 

[WebServer]
port = 8080
